### ISSUE TITLE
Error when creating database

### ISSUE THREAD

**Issue by xperignon** [ricardocabral/iskdaemon#60]
With 0.9.3 (compiled) on debian squeeze :, when creating database "bonjour" :

root@xp:~# iskdaemon.py
isk-daemon  : INFO     | using config file "/etc/iskdaemon/isk-daemon.conf"
imgdbapi    : INFO     +- Initializing isk-daemon server (version 0.9.3) ...
imageDB     : DEBUG    | loadalldbs(fname='/data/isk/isk-db')
imageDB     : DEBUG    | Database (/data/isk/isk-db) loaded with 0 spaces
imgdbapi    : INFO     | image database initialized
iskdaemon   : INFO     +- Starting HTTP service endpoints...
iskdaemon   : INFO     | serving web admin from /usr/local/lib/python2.6/dist-packages/isk_daemon-0.9.3-py2.6-linux-x86_64.egg/ui/admin-www
iskdaemon   : INFO     | web admin interface listening for requests at http://localhost:31128/
iskdaemon   : INFO     | listening for SOAP requests at http://localhost:31128/SOAP
iskdaemon   : INFO     | listening for XML-RPC requests at http://localhost:31128/RPC
iskdaemon   : DEBUG    | listening for data export requests at http://localhost:31128/export
iskdaemon   : INFO     | HTTP service endpoints started. Binded to all local network interfaces.
iskdaemon   : DEBUG    +- Starting internal service endpoint...
iskdaemon   : DEBUG    | internal service listener started at pb://localhost:31228
iskdaemon   : INFO     | Binded to all local network interfaces.
iskdaemon   : INFO     + init finished. Waiting for requests ...
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Twisted-13.1.0-py2.6-linux-x86_64.egg/twisted/web/server.py", line 189, in process
    self.render(resrc)
  File "/usr/local/lib/python2.6/dist-packages/Twisted-13.1.0-py2.6-linux-x86_64.egg/twisted/web/server.py", line 238, in render
    body = resrc.render(self)
  File "/usr/local/lib/python2.6/dist-packages/Twisted-13.1.0-py2.6-linux-x86_64.egg/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python2.6/dist-packages/Twisted-13.1.0-py2.6-linux-x86_64.egg/twisted/web/xmlrpc.py", line 172, in render_POST
    d = defer.maybeDeferred(function, _args)
--- <exception caught here> ---
  File "/usr/local/lib/python2.6/dist-packages/Twisted-13.1.0-py2.6-linux-x86_64.egg/twisted/internet/defer.py", line 137, in maybeDeferred
    result = f(_args, **kw)
  File "/usr/local/lib/python2.6/dist-packages/isk_daemon-0.9.3-py2.6-linux-x86_64.egg/core/imgdbapi.py", line 304, in createDb
    dbId = int(dbId)
exceptions.ValueError: invalid literal for int() with base 10: 'bonjour'

^CimageDB     : DEBUG    | savealldbs(fname='/data/isk/isk-db')
imageDB     : ERROR    Error saving image database
imageDB     : DEBUG    | closedb()
imgdbapi    : INFO     Shuting instance down...

And webUI displays :

Unexpected error: Server returned response code 0 - null Unknown.ob(Unknown Source) Unknown.rb(Unknown Source) Unknown.Kb(Unknown Source) Unknown.Qi(Unknown Source) Unknown.pj(Unknown Source) Unknown.<anonymous>(Unknown Source) Unknown.wd(Unknown Source) Unknown.zd(Unknown Source) Unknown.<anonymous>(Unknown Source)

**Comment by tegansnyder** [comment]
For some reason I had the same issue. When I changed the database location in /etc/iskdaemon/isk-daemon.conf the I got the error about `imageDB : ERROR Error saving image database`.

I decided to disable conf file by moving it to `.old`.

``` sh
mv /etc/iskdaemon/isk-daemon.conf /etc/iskdaemon/isk-daemon.conf.old
```

I then manually edited the core settings file and changed the database path by editing:

```
/usr/lib/python2.6/site-packages/isk_daemon-0.9.5-py2.6-linux-x86_64.egg/core/settings.py
```

It started fine then.

**Comment by anti1869** [comment]
Do you mean settings.py, not *.pyc? (because `pyc` is for temp file with bytecode for python modules).

What location did you tried to point in your isk-daemon.conf? Do you have write access to this location?

Could you please provide log with this error if it happens again

**Comment by tegansnyder** [comment]
Yes I meant `settings.py`. I did have write access to the location under the current running user. If I encounter it again I will provide a log.
