### ISSUE TITLE
isk-daemon and ubuntu 16.04

### ISSUE THREAD

**Issue by Turbin-SE** [ricardocabral/iskdaemon#74]
I'm having some trouble getting the isk-daemon running on ubuntu 16.04.
Version 0.9.3 compiles and installs if I install the 'graphicsmagick-libmagick-dev-compat' compability package that enables 'Magick++-config'.

But the server crashes whenever I try to add an image to the database. This is the error message I receive:

`python: magick/semaphore.c:601: LockSemaphoreInfo: Assertion 'semaphore_info != (SemaphoreInfo *) ((void *)0)' failed.`

I downloaded the source from here and tried to compile it. But (I think) something goes wrong when the output from "Magick+++-config" gets parsed. This is the error i get from "python setup.py build":

`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c imgSeekLib/imgdb.cpp -o build/temp.linux-x86_64-2.7/imgSeekLib/imgdb.o -DImMagick -DLinuxBuild -g - W a l l - g - f n o - s t r i c t - a l i a s i n g - O 2 - p t h r e a d - I / u s r / i n c l u d e / G r a p h i c s M a g i c k`

As you can see I get spaces between some of the instructions. Not sure why.

Any help would be greatly appreciated!
I have a couple of cron scripts that depend on the isk-daemon running. So right now much of the functionality of my server is dead.

Thanks!

/Peter

Here's the complete output from building the latest (and greatest) isk-daemon:

```
#################################### Check ImageMagick
Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    include_dirs.append([i[2:] for i in IMagCFlag.split(' ') if i.startswith("-I")][0])
IndexError: list index out of range
Found the following arguments:
extra_compile_args ['-DImMagick', '-DLinuxBuild', '-g', '-', 'W', 'a', 'l', 'l', '-', 'g', '-', 'f', 'n', 'o', '-', 's', 't', 'r', 'i', 'c', 't', '-', 'a', 'l', 'i', 'a', 's', 'i', 'n', 'g', '-', 'O', '2', '-', 'p', 't', 'h', 'r', 'e', 'a', 'd', '-', 'I', '/', 'u', 's', 'r', '/', 'i', 'n', 'c', 'l', 'u', 'd', 'e', '/', 'G', 'r', 'a', 'p', 'h', 'i', 'c', 's', 'M', 'a', 'g', 'i', 'c', 'k']
extra_link_args ['-g']
#################################### Installing
running build
running build_py
file imgdb.py (for module imgdb) not found
copying imgSeekLib/imgdb.py -> build/lib.linux-x86_64-2.7/imgSeekLib
file imgdb.py (for module imgdb) not found
running build_ext
building '_imgdb' extension
swigging imgSeekLib/imgdb.i to imgSeekLib/imgdb_wrap.cpp
swig -python -c++ -o imgSeekLib/imgdb_wrap.cpp imgSeekLib/imgdb.i
imgSeekLib/imgdb.i:97: Warning 362: operator= ignored
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c imgSeekLib/imgdb.cpp -o build/temp.linux-x86_64-2.7/imgSeekLib/imgdb.o -DImMagick -DLinuxBuild -g - W a l l - g - f n o - s t r i c t - a l i a s i n g - O 2 - p t h r e a d - I / u s r / i n c l u d e / G r a p h i c s M a g i c k
x86_64-linux-gnu-gcc: error: W: No such file or directory
x86_64-linux-gnu-gcc: error: a: No such file or directory
x86_64-linux-gnu-gcc: error: l: No such file or directory
x86_64-linux-gnu-gcc: error: l: No such file or directory
x86_64-linux-gnu-gcc: error: g: No such file or directory
x86_64-linux-gnu-gcc: error: f: No such file or directory
x86_64-linux-gnu-gcc: error: n: No such file or directory
x86_64-linux-gnu-gcc: error: o: No such file or directory
x86_64-linux-gnu-gcc: error: s: No such file or directory
x86_64-linux-gnu-gcc: error: t: No such file or directory
x86_64-linux-gnu-gcc: error: r: No such file or directory
x86_64-linux-gnu-gcc: error: i: No such file or directory
x86_64-linux-gnu-gcc: error: c: No such file or directory
x86_64-linux-gnu-gcc: error: t: No such file or directory
x86_64-linux-gnu-gcc: error: a: No such file or directory
x86_64-linux-gnu-gcc: error: l: No such file or directory
x86_64-linux-gnu-gcc: error: i: No such file or directory
x86_64-linux-gnu-gcc: error: a: No such file or directory
x86_64-linux-gnu-gcc: error: s: No such file or directory
x86_64-linux-gnu-gcc: error: i: No such file or directory
x86_64-linux-gnu-gcc: error: n: No such file or directory
x86_64-linux-gnu-gcc: error: g: No such file or directory
x86_64-linux-gnu-gcc: error: O: No such file or directory
x86_64-linux-gnu-gcc: error: 2: No such file or directory
x86_64-linux-gnu-gcc: error: p: No such file or directory
x86_64-linux-gnu-gcc: error: t: No such file or directory
x86_64-linux-gnu-gcc: error: h: No such file or directory
x86_64-linux-gnu-gcc: error: r: No such file or directory
x86_64-linux-gnu-gcc: error: e: No such file or directory
x86_64-linux-gnu-gcc: error: a: No such file or directory
x86_64-linux-gnu-gcc: error: d: No such file or directory
x86_64-linux-gnu-gcc: error: I: No such file or directory
x86_64-linux-gnu-gcc: error: u: No such file or directory
x86_64-linux-gnu-gcc: error: s: No such file or directory
x86_64-linux-gnu-gcc: error: r: No such file or directory
x86_64-linux-gnu-gcc: error: i: No such file or directory
x86_64-linux-gnu-gcc: error: n: No such file or directory
x86_64-linux-gnu-gcc: error: c: No such file or directory
x86_64-linux-gnu-gcc: error: l: No such file or directory
x86_64-linux-gnu-gcc: error: u: No such file or directory
x86_64-linux-gnu-gcc: error: d: No such file or directory
x86_64-linux-gnu-gcc: error: e: No such file or directory
x86_64-linux-gnu-gcc: error: G: No such file or directory
x86_64-linux-gnu-gcc: error: r: No such file or directory
x86_64-linux-gnu-gcc: error: a: No such file or directory
x86_64-linux-gnu-gcc: error: p: No such file or directory
x86_64-linux-gnu-gcc: error: h: No such file or directory
x86_64-linux-gnu-gcc: error: i: No such file or directory
x86_64-linux-gnu-gcc: error: c: No such file or directory
x86_64-linux-gnu-gcc: error: s: No such file or directory
x86_64-linux-gnu-gcc: error: M: No such file or directory
x86_64-linux-gnu-gcc: error: a: No such file or directory
x86_64-linux-gnu-gcc: error: g: No such file or directory
x86_64-linux-gnu-gcc: error: i: No such file or directory
x86_64-linux-gnu-gcc: error: c: No such file or directory
x86_64-linux-gnu-gcc: error: k: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 96, in run
    build_ext.run(self)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 498, in build_extension
    depends=ext.depends)
  File "/usr/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python2.7/distutils/unixccompiler.py", line 124, in _compile
    raise CompileError, msg
CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
running build_scripts
See http://www.imgseek.net/isk-daemon/documents-1/usage for some next steps.
See http://www.imgseek.net/isk-daemon/documents-1/faq for some common questions.
```

**Comment by FabriceNeyret** [comment]
The cause might be something else. according to https://sourceforge.net/p/graphicsmagick/support-requests/27/ , you now really need to call InitializeMagick  ( e.g. InitializeMagick(""); ) prior to any use.
ref: http://www.graphicsmagick.org/Magick++/#api
At least in C++ I had exactly the same error message, that this fix solved.
